<?php

namespace App\Database\Seeds;

use App\Models\CompanyModel;
use CodeIgniter\Database\Seeder;

class CompanyDiscoverySeeder extends Seeder
{
    public function run(): void
    {
        $companyModel = new CompanyModel();
        $now = date('Y-m-d H:i:s');

        $companies = [
            [
                'name' => 'Wipro',
                'website' => 'https://www.wipro.com',
                'industry' => 'Information Technology Services',
                'company_type' => 'Indian MNC',
                'company_tags' => 'indian mnc, enterprise, services, consulting, global indian',
                'size' => '10000+',
                'founded_year' => '1945',
                'hq' => 'Bengaluru, Karnataka',
                'branches' => 'Bengaluru, Chennai, Hyderabad, Pune, Kochi, Mumbai, Gurugram',
                'short_description' => 'Indian multinational technology services and consulting company with global delivery teams.',
                'what_we_do' => 'Technology consulting, digital transformation, cloud, engineering, cybersecurity, and managed services.',
                'profile_status' => 'public_seed',
                'is_featured' => 1,
            ],
            [
                'name' => 'Tata Consultancy Services',
                'website' => 'https://www.tcs.com',
                'industry' => 'Information Technology Services',
                'company_type' => 'Indian MNC',
                'company_tags' => 'indian mnc, enterprise, services, consulting, global indian',
                'size' => '10000+',
                'founded_year' => '1968',
                'hq' => 'Mumbai, Maharashtra',
                'branches' => 'Mumbai, Bengaluru, Chennai, Hyderabad, Pune, Kochi, Kolkata, Delhi NCR',
                'short_description' => 'Large Indian IT services, consulting, and business solutions company.',
                'what_we_do' => 'IT services, consulting, business process services, cloud, analytics, and enterprise platforms.',
                'profile_status' => 'public_seed',
                'is_featured' => 1,
            ],
            [
                'name' => 'Infosys',
                'website' => 'https://www.infosys.com',
                'industry' => 'Information Technology Services',
                'company_type' => 'Indian MNC',
                'company_tags' => 'indian mnc, enterprise, services, consulting, global indian',
                'size' => '10000+',
                'founded_year' => '1981',
                'hq' => 'Bengaluru, Karnataka',
                'branches' => 'Bengaluru, Mysuru, Pune, Chennai, Hyderabad, Thiruvananthapuram, Mangaluru',
                'short_description' => 'Digital services and consulting company serving global enterprise clients.',
                'what_we_do' => 'Digital transformation, cloud, AI, consulting, engineering, and enterprise application services.',
                'profile_status' => 'public_seed',
                'is_featured' => 1,
            ],
            [
                'name' => 'HCLTech',
                'website' => 'https://www.hcltech.com',
                'industry' => 'Information Technology Services',
                'company_type' => 'Indian MNC',
                'company_tags' => 'indian mnc, enterprise, services, engineering, global indian',
                'size' => '10000+',
                'founded_year' => '1976',
                'hq' => 'Noida, Uttar Pradesh',
                'branches' => 'Noida, Chennai, Bengaluru, Hyderabad, Pune, Madurai, Lucknow',
                'short_description' => 'Technology company focused on digital, engineering, cloud, and software services.',
                'what_we_do' => 'Engineering services, cloud, digital workplace, application services, and cybersecurity.',
                'profile_status' => 'public_seed',
                'is_featured' => 1,
            ],
            [
                'name' => 'Tech Mahindra',
                'website' => 'https://www.techmahindra.com',
                'industry' => 'Information Technology Services',
                'company_type' => 'Indian MNC',
                'company_tags' => 'indian mnc, enterprise, services, telecom, global indian',
                'size' => '10000+',
                'founded_year' => '1986',
                'hq' => 'Pune, Maharashtra',
                'branches' => 'Pune, Bengaluru, Hyderabad, Chennai, Mumbai, Noida',
                'short_description' => 'Indian technology consulting and digital solutions company.',
                'what_we_do' => 'Digital transformation, IT services, telecom solutions, customer experience, and engineering.',
                'profile_status' => 'public_seed',
                'is_featured' => 1,
            ],
            [
                'name' => 'Zoho',
                'website' => 'https://www.zoho.com',
                'industry' => 'Software Product',
                'company_type' => 'Product Company',
                'company_tags' => 'product, saas, indian product, global indian, remote friendly',
                'size' => '10000+',
                'founded_year' => '1996',
                'hq' => 'Chennai, Tamil Nadu',
                'branches' => 'Chennai, Tenkasi, Coimbatore, Bengaluru, Hyderabad',
                'short_description' => 'Indian software product company building SaaS products for businesses worldwide.',
                'what_we_do' => 'CRM, finance, collaboration, HR, low-code, analytics, and business software products.',
                'profile_status' => 'public_seed',
                'is_featured' => 1,
            ],
            [
                'name' => 'Freshworks',
                'website' => 'https://www.freshworks.com',
                'industry' => 'Software Product',
                'company_type' => 'Product Company',
                'company_tags' => 'product, saas, startup, global indian, remote friendly',
                'size' => '5001-10000',
                'founded_year' => '2010',
                'hq' => 'Chennai, Tamil Nadu',
                'branches' => 'Chennai, Bengaluru, Hyderabad',
                'short_description' => 'SaaS company offering customer support, IT service, sales, and marketing products.',
                'what_we_do' => 'Customer experience software, IT service management, CRM, automation, and AI-assisted support.',
                'profile_status' => 'public_seed',
                'is_featured' => 1,
            ],
            [
                'name' => 'Razorpay',
                'website' => 'https://razorpay.com',
                'industry' => 'Fintech',
                'company_type' => 'Startup',
                'company_tags' => 'startup, fintech, product, unicorn, payments, remote friendly',
                'size' => '1001-5000',
                'founded_year' => '2014',
                'hq' => 'Bengaluru, Karnataka',
                'branches' => 'Bengaluru, Mumbai, Delhi NCR',
                'short_description' => 'Fintech company building payment, banking, and financial infrastructure for businesses.',
                'what_we_do' => 'Payment gateway, payment links, subscriptions, business banking, payouts, and fintech APIs.',
                'profile_status' => 'public_seed',
                'is_featured' => 1,
            ],
            [
                'name' => 'PhonePe',
                'website' => 'https://www.phonepe.com',
                'industry' => 'Fintech',
                'company_type' => 'Product Company',
                'company_tags' => 'product, fintech, payments, startup, unicorn',
                'size' => '5001-10000',
                'founded_year' => '2015',
                'hq' => 'Bengaluru, Karnataka',
                'branches' => 'Bengaluru, Pune, Mumbai, Delhi NCR',
                'short_description' => 'Digital payments and financial services platform in India.',
                'what_we_do' => 'UPI payments, bill payments, merchant solutions, insurance, lending, and financial services.',
                'profile_status' => 'public_seed',
                'is_featured' => 1,
            ],
            [
                'name' => 'Flipkart',
                'website' => 'https://www.flipkart.com',
                'industry' => 'E-commerce',
                'company_type' => 'Corporate',
                'company_tags' => 'ecommerce, product, corporate, startup, marketplace',
                'size' => '10000+',
                'founded_year' => '2007',
                'hq' => 'Bengaluru, Karnataka',
                'branches' => 'Bengaluru, Delhi NCR, Mumbai, Hyderabad, Chennai',
                'short_description' => 'Indian e-commerce marketplace with technology, supply chain, and seller platforms.',
                'what_we_do' => 'Online marketplace, logistics technology, seller services, payments, and consumer commerce.',
                'profile_status' => 'public_seed',
                'is_featured' => 1,
            ],
            [
                'name' => 'Zerodha',
                'website' => 'https://zerodha.com',
                'industry' => 'Fintech',
                'company_type' => 'Product Company',
                'company_tags' => 'product, fintech, brokerage, startup, bootstrapped',
                'size' => '1001-5000',
                'founded_year' => '2010',
                'hq' => 'Bengaluru, Karnataka',
                'branches' => 'Bengaluru',
                'short_description' => 'Technology-led stock brokerage and investment platform.',
                'what_we_do' => 'Trading platforms, investment products, market education, APIs, and financial technology.',
                'profile_status' => 'public_seed',
                'is_featured' => 1,
            ],
            [
                'name' => 'Swiggy',
                'website' => 'https://www.swiggy.com',
                'industry' => 'Consumer Internet',
                'company_type' => 'Startup',
                'company_tags' => 'startup, consumer internet, delivery, product, marketplace',
                'size' => '5001-10000',
                'founded_year' => '2014',
                'hq' => 'Bengaluru, Karnataka',
                'branches' => 'Bengaluru, Hyderabad, Chennai, Mumbai, Delhi NCR, Pune, Kochi',
                'short_description' => 'Consumer internet company focused on food delivery, quick commerce, and logistics technology.',
                'what_we_do' => 'Food delivery, quick commerce, restaurant technology, logistics, and consumer platforms.',
                'profile_status' => 'public_seed',
                'is_featured' => 1,
            ],
            [
                'name' => 'Zomato',
                'website' => 'https://www.zomato.com',
                'industry' => 'Consumer Internet',
                'company_type' => 'Corporate',
                'company_tags' => 'consumer internet, foodtech, product, marketplace, startup',
                'size' => '5001-10000',
                'founded_year' => '2008',
                'hq' => 'Gurugram, Haryana',
                'branches' => 'Gurugram, Bengaluru, Mumbai, Hyderabad, Pune, Chennai',
                'short_description' => 'Food discovery, delivery, and restaurant technology company.',
                'what_we_do' => 'Food ordering, restaurant discovery, dining services, quick commerce, and merchant tools.',
                'profile_status' => 'public_seed',
                'is_featured' => 1,
            ],
            [
                'name' => 'Reliance Industries',
                'website' => 'https://www.ril.com',
                'industry' => 'Conglomerate',
                'company_type' => 'Corporate',
                'company_tags' => 'corporate, conglomerate, energy, telecom, retail, indian mnc',
                'size' => '10000+',
                'founded_year' => '1973',
                'hq' => 'Mumbai, Maharashtra',
                'branches' => 'Mumbai, Jamnagar, Navi Mumbai, Bengaluru, Delhi NCR',
                'short_description' => 'Indian conglomerate with businesses across energy, retail, telecom, digital, and materials.',
                'what_we_do' => 'Energy, petrochemicals, retail, telecom, digital platforms, and consumer businesses.',
                'profile_status' => 'public_seed',
                'is_featured' => 1,
            ],
            [
                'name' => 'Mahindra Group',
                'website' => 'https://www.mahindra.com',
                'industry' => 'Automotive and Conglomerate',
                'company_type' => 'Corporate',
                'company_tags' => 'corporate, manufacturing, automotive, indian mnc, global indian',
                'size' => '10000+',
                'founded_year' => '1945',
                'hq' => 'Mumbai, Maharashtra',
                'branches' => 'Mumbai, Pune, Chennai, Bengaluru, Nashik, Jaipur',
                'short_description' => 'Indian group with businesses in automotive, farm equipment, technology, finance, and more.',
                'what_we_do' => 'Automotive, tractors, farm equipment, financial services, IT, hospitality, and mobility.',
                'profile_status' => 'public_seed',
                'is_featured' => 0,
            ],
            [
                'name' => 'Larsen & Toubro',
                'website' => 'https://www.larsentoubro.com',
                'industry' => 'Engineering and Construction',
                'company_type' => 'Corporate',
                'company_tags' => 'corporate, engineering, infrastructure, manufacturing, indian mnc',
                'size' => '10000+',
                'founded_year' => '1938',
                'hq' => 'Mumbai, Maharashtra',
                'branches' => 'Mumbai, Chennai, Bengaluru, Vadodara, Hyderabad, Delhi NCR',
                'short_description' => 'Indian engineering, construction, manufacturing, technology, and financial services group.',
                'what_we_do' => 'Infrastructure, engineering projects, manufacturing, defence, technology, and construction.',
                'profile_status' => 'public_seed',
                'is_featured' => 0,
            ],
            [
                'name' => 'Biocon',
                'website' => 'https://www.biocon.com',
                'industry' => 'Healthcare and Biotechnology',
                'company_type' => 'Corporate',
                'company_tags' => 'corporate, healthcare, biotech, pharma, global indian',
                'size' => '5001-10000',
                'founded_year' => '1978',
                'hq' => 'Bengaluru, Karnataka',
                'branches' => 'Bengaluru, Hyderabad, Chennai',
                'short_description' => 'Biopharmaceutical company focused on affordable healthcare and biotechnology-led medicines.',
                'what_we_do' => 'Biologics, biosimilars, research, manufacturing, and biopharmaceutical products.',
                'profile_status' => 'public_seed',
                'is_featured' => 0,
            ],
            [
                'name' => 'Dr. Reddy\'s Laboratories',
                'website' => 'https://www.drreddys.com',
                'industry' => 'Pharmaceuticals',
                'company_type' => 'Indian MNC',
                'company_tags' => 'indian mnc, pharma, healthcare, global indian, corporate',
                'size' => '10000+',
                'founded_year' => '1984',
                'hq' => 'Hyderabad, Telangana',
                'branches' => 'Hyderabad, Bengaluru, Mumbai, Visakhapatnam',
                'short_description' => 'Indian pharmaceutical company with global generics, APIs, and healthcare products.',
                'what_we_do' => 'Generic medicines, active pharmaceutical ingredients, biosimilars, and pharma research.',
                'profile_status' => 'public_seed',
                'is_featured' => 0,
            ],
            [
                'name' => 'Mphasis',
                'website' => 'https://www.mphasis.com',
                'industry' => 'Information Technology Services',
                'company_type' => 'Indian MNC',
                'company_tags' => 'indian mnc, services, enterprise, cloud, global indian',
                'size' => '10000+',
                'founded_year' => '1998',
                'hq' => 'Bengaluru, Karnataka',
                'branches' => 'Bengaluru, Chennai, Pune, Mumbai, Hyderabad, Mangaluru',
                'short_description' => 'IT services company focused on cloud, cognitive services, and enterprise transformation.',
                'what_we_do' => 'Application services, cloud, data, AI, infrastructure, and business process services.',
                'profile_status' => 'public_seed',
                'is_featured' => 0,
            ],
            [
                'name' => 'MakeMyTrip',
                'website' => 'https://www.makemytrip.com',
                'industry' => 'Travel Technology',
                'company_type' => 'Product Company',
                'company_tags' => 'product, traveltech, consumer internet, global indian',
                'size' => '1001-5000',
                'founded_year' => '2000',
                'hq' => 'Gurugram, Haryana',
                'branches' => 'Gurugram, Bengaluru, Mumbai',
                'short_description' => 'Online travel company offering booking products for flights, hotels, holidays, and transport.',
                'what_we_do' => 'Travel booking platforms, hotel inventory, holiday packages, transport, and travel technology.',
                'profile_status' => 'public_seed',
                'is_featured' => 0,
            ],
            [
                'name' => 'CRED',
                'website' => 'https://cred.club',
                'industry' => 'Fintech',
                'company_type' => 'Startup',
                'company_tags' => 'startup, fintech, product, consumer internet, remote friendly',
                'size' => '1001-5000',
                'founded_year' => '2018',
                'hq' => 'Bengaluru, Karnataka',
                'branches' => 'Bengaluru',
                'short_description' => 'Fintech platform focused on credit card payments, rewards, and financial products.',
                'what_we_do' => 'Consumer fintech, payments, rewards, credit products, and personal finance experiences.',
                'profile_status' => 'public_seed',
                'is_featured' => 0,
            ],
            [
                'name' => 'Meesho',
                'website' => 'https://www.meesho.com',
                'industry' => 'E-commerce',
                'company_type' => 'Startup',
                'company_tags' => 'startup, ecommerce, marketplace, consumer internet, product',
                'size' => '1001-5000',
                'founded_year' => '2015',
                'hq' => 'Bengaluru, Karnataka',
                'branches' => 'Bengaluru',
                'short_description' => 'E-commerce marketplace focused on value commerce and seller enablement.',
                'what_we_do' => 'Marketplace technology, seller tools, logistics, catalog systems, and consumer commerce.',
                'profile_status' => 'public_seed',
                'is_featured' => 0,
            ],
            [
                'name' => 'Postman',
                'website' => 'https://www.postman.com',
                'industry' => 'Developer Tools',
                'company_type' => 'Product Company',
                'company_tags' => 'product, saas, developer tools, global indian, remote friendly',
                'size' => '501-1000',
                'founded_year' => '2014',
                'hq' => 'Bengaluru, Karnataka',
                'branches' => 'Bengaluru, San Francisco, remote',
                'short_description' => 'API platform company with roots in India and a global developer user base.',
                'what_we_do' => 'API development, testing, documentation, collaboration, and platform tooling.',
                'profile_status' => 'public_seed',
                'is_featured' => 0,
            ],
        ];

        foreach ($companies as $company) {
            $company['data_source_note'] = 'Starter public-profile seed. Verify details before marking as verified.';
            $company['is_verified'] = 0;
            $company['contact_public'] = 0;
            $company['created_at'] = $now;
            $company['updated_at'] = $now;

            $companyModel->upsertByName($company['name'], $company);
        }
    }
}
